version: '3.3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DATABASE: 'postgres'
      # So you don't have to use root, but you can if you like
      POSTGRES_USER: 'postgres'
      # You can use whatever password you like
      POSTGRES_PASSWORD: '123'
      # Password for root access
      POSTGRES_ROOT_PASSWORD: '123'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '5432:5432'
    expose:
      # Opens port 3306 on the container
      - '5432'
      # Where our data will be persisted
    volumes:
      - pg_data:/var/lib/postgresql/data
# Names our volume
volumes:
  pg_data: